const fs = require('fs');
const path = require('path');

// 1. Read variables from Vercel Environment
const geminiKey = process.env.GEMINI_KEY || 'MISSING_KEY';
const emailService = process.env.EMAILJS_SERVICE_ID || 'MISSING_SERVICE';
const emailTemplate = process.env.EMAILJS_TEMPLATE_ID || 'MISSING_TEMPLATE';
const emailPublic = process.env.EMAILJS_PUBLIC_KEY || 'MISSING_PUBLIC';

// 2. Format the file content
// We use export const CONFIG just like the local dev file
const content = `
// 🔒 GENERATED BY VERCEL BUILD - DO NOT EDIT MANUALLY
export const CONFIG = {
    GEMINI_KEY: '${geminiKey}',
    EMAILJS: {
        SERVICE_ID: '${emailService}',
        TEMPLATE_ID: '${emailTemplate}',
        PUBLIC_KEY: '${emailPublic}'
    }
};
`;

// 3. BUILD PROCESS
const publicDir = path.join(__dirname, 'public');
const assetsDir = path.join(publicDir, 'assets');
const jsDir = path.join(assetsDir, 'js');
const configFile = path.join(jsDir, 'config.js');

try {
    console.log('🚀 Starting Build Process...');

    // A. Clean/Create Public Directory
    if (fs.existsSync(publicDir)) {
        fs.rmSync(publicDir, { recursive: true, force: true });
    }
    fs.mkdirSync(publicDir);

    // B. Copy Static Files
    console.log('📂 Copying files to public/...');

    // Copy HTML files
    fs.copyFileSync(path.join(__dirname, 'index.html'), path.join(publicDir, 'index.html'));
    fs.copyFileSync(path.join(__dirname, 'about.html'), path.join(publicDir, 'about.html'));

    // Copy Assets (Recursive)
    fs.cpSync(path.join(__dirname, 'assets'), assetsDir, { recursive: true });

    // C. Generate Config File (Securely)
    // Note: We overwrite the one in public/assets/js, not source
    console.log('🔐 Generating secure config.js...');
    fs.writeFileSync(configFile, content);

    console.log('✅ Build Complete! Output directory: ./public');

} catch (error) {
    console.error('❌ Build Failed:', error);
    process.exit(1);
}
