const fs = require('fs');
const path = require('path');

// 1. Read variables from Vercel Environment
const geminiKey = process.env.GEMINI_KEY || 'MISSING_KEY';
const emailService = process.env.EMAILJS_SERVICE_ID || 'MISSING_SERVICE';
const emailTemplate = process.env.EMAILJS_TEMPLATE_ID || 'MISSING_TEMPLATE';
const emailPublic = process.env.EMAILJS_PUBLIC_KEY || 'MISSING_PUBLIC';

// 2. Format the file content
// We use export const CONFIG just like the local dev file
const content = `
// 🔒 GENERATED BY VERCEL BUILD - DO NOT EDIT MANUALLY
export const CONFIG = {
    GEMINI_KEY: '${geminiKey}',
    EMAILJS: {
        SERVICE_ID: '${emailService}',
        TEMPLATE_ID: '${emailTemplate}',
        PUBLIC_KEY: '${emailPublic}'
    }
};
`;

// 3. Write the file
const dir = path.join(__dirname, 'assets', 'js');
const filePath = path.join(dir, 'config.js');

try {
    // Ensure directory exists
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(filePath, content);
    console.log('✅ assets/js/config.js successfully generated from Environment Variables.');
} catch (error) {
    console.error('❌ Error generating config.js:', error);
    process.exit(1);
}
